name: ${project.name}
main: plugily.projects.thebridge.Main
authors: [ Tigerpanzer, 2Wild4You, sidious38 ]
version: ${project.version}
api-version: 1.13
softdepend: [ PlaceholderAPI ]

commands:
  thebridge:
    description: thebridge commands
    aliases: [ tb, bridge ]
  thebridgeAdmin:
    description: thebridge admin commands
    aliases: [ tba, bridgeadmin ]